matrix:
- name: Markdown
  aspell:
    lang: en
  dictionary:
    wordlists:
    - doc/.wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.context:
      context_visible_first: true
      delimiters:
      # Ignore shortcodes {{< and >}}
      - open: '(?s)(?P<open> *\{{2,}<)'
        close: '^(?P=open)$'
      # Ignore text between inline back ticks
      - open: '(?s)(?P<open> *>\}{2,})'
        close: '(?P=open)'    
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
      - img
  sources:
  - '**/*.md'
  default_encoding: utf-8
