name: generate-feeder-pcb-artifacts

on:
  push:
    paths:
    - 'feeder/pcb/**.sch'
    - 'feeder/pcb/**.kicad_pcb'
    - 'feeder/pcb/**.kibot.yaml'
    - '.github/workflows/generate-feeder-pcb-artifacts.yaml'
    - '**.kibot.yaml'
  pull_request:
    paths:
    - 'feeder/pcb/**.sch'
    - 'feeder/pcb/**.kicad_pcb'
    - 'feeder/pcb/**.kibot.yaml'
    - '.github/workflows/generate-feeder-pcb-artifacts.yaml'
    - '**.kibot.yaml'

jobs:
  ERC:
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto:latest
      
    steps:
    - name: Update system repositories
      run:  apt update

    - name: Install Required Libraries
      run: apt -y install git zip librsvg2-bin imagemagick

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run feeder mobo KiBot
      run: cd feeder/pcb/mobo && kibot -c ../../../config.kibot.yaml -d export

    - name: Compress feeder mobo Gerbers for PCB Fab
      run: cd feeder/pcb/mobo/export/gerbers && zip -r -j ../feeder_mobo_gerbers.zip *

    - name: Run indexingWheel KiBot
      run: cd feeder/pcb/indexingWheel && kibot -c ../../../config-blank.kibot.yaml -d export

    - name: Compress indexingWheel Gerbers for PCB Fab
      run: cd feeder/pcb/indexingWheel/export/gerbers && zip -r -j ../feeder_indexingWheel_gerbers.zip *

    - name: Run feederFloor KiBot
      run: cd feeder/pcb/feederFloor && kibot -c ../../../config.kibot.yaml -d export

    - name: Compress feederFloor Gerbers for PCB Fab
      run: cd feeder/pcb/feederFloor/export/gerbers && zip -r -j ../feeder_feederFloor_gerbers.zip *

    - name: Commit files
      if: github.event_name == 'push'
      run: |
        git add -f feeder/pcb/mobo/export
        git add -f feeder/pcb/indexingWheel/export
        git add -f feeder/pcb/feederFloor/export
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "CI: Generate Gerbers and Associated Artifacts" -a | exit 0

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
      if: github.event_name == 'push'
